#!/bin/bash
# Quick deployment guide for Render

echo "🚀 AI Counsellor - Quick Deployment to Render"
echo "=============================================="
echo ""
echo "STEP 1: Push code to GitHub"
echo "  - Make sure you have a GitHub account"
echo "  - Create a new repository"
echo "  - Push your code:"
echo ""
echo "    git init"
echo "    git add ."
echo "    git commit -m 'Initial commit: AI Counsellor'"
echo "    git branch -M main"
echo "    git remote add origin https://github.com/YOUR_USERNAME/ai-counsellor.git"
echo "    git push -u origin main"
echo ""
echo "STEP 2: Get Anthropic API Key"
echo "  - Visit: https://console.anthropic.com"
echo "  - Sign up (free tier available)"
echo "  - Generate API key"
echo "  - Save it securely"
echo ""
echo "STEP 3: Deploy Backend to Render"
echo "  - Go to: https://render.com"
echo "  - Click 'New +' → 'Web Service'"
echo "  - Connect your GitHub repository"
echo "  - Configure:"
echo "    Name: ai-counsellor-backend"
echo "    Environment: Python"
echo "    Build Command: pip install -r requirements.txt && python seed_comprehensive.py"
echo "    Start Command: uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "  - Add Environment Variables:"
echo "    DATABASE_URL=sqlite:///./counsellor.db"
echo "    SECRET_KEY=your-super-secret-key"
echo "    ANTHROPIC_API_KEY=your-api-key"
echo ""
echo "  - Deploy (takes 2-3 minutes)"
echo ""
echo "STEP 4: Deploy Frontend to Vercel"
echo "  - Go to: https://vercel.com"
echo "  - Click 'Add New' → 'Project'"
echo "  - Import your GitHub repository"
echo "  - Configure:"
echo "    Framework: Vite (or Other)"
echo "    Build Command: npm run build"
echo "    Output Directory: dist"
echo ""
echo "  - Add Environment Variable:"
echo "    VITE_API_URL=https://your-backend-url.onrender.com"
echo ""
echo "  - Deploy (automatic)"
echo ""
echo "STEP 5: Get Your Links!"
echo "  - Backend: https://your-backend.onrender.com"
echo "  - Frontend: https://your-frontend.vercel.app"
echo ""
echo "=============================================="
echo ""
echo "⏱️  Total deployment time: ~5 minutes"
echo ""
